// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TestKommentSayavkaWithNormEmailTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void testKommentSayavkaWithNormEmail() {
    driver.Navigate().GoToUrl("https://mypollycoffee.tilda.ws");
    driver.Manage().Window.Size = new System.Drawing.Size(1082, 800);
    driver.FindElement(By.Id("input_3446643282700")).Click();
    driver.FindElement(By.Id("input_3446643282700")).SendKeys("dfghj");
    driver.FindElement(By.Id("input_3446643282701")).Click();
    driver.FindElement(By.Id("input_3446643282701")).SendKeys("p2200220022@gmail.com");
    driver.FindElement(By.Id("input_3456643282702")).Click();
    driver.FindElement(By.Id("input_3456643282702")).SendKeys("34567890");
    driver.FindElement(By.Id("input_1699452000573")).Click();
    driver.FindElement(By.Id("input_1699452000573")).SendKeys("sdfghjkokp");
    driver.FindElement(By.CssSelector(".t-form__submit:nth-child(6) > .t-submit")).Click();
  }
}
